### ISSUE TITLE
Possible Easy Fix for Int / Enum Problem Mentioned in Readme

### ISSUE THREAD

**Issue by julian-irwin-tfs** [MREYE-LUMC/ZOSPy#8] opened 2023-02-15 19:40 UTC
While running the example `ZOSPy\examples\Escudero-Sanz eye model\Escudero-Sanz eye model.ipynb` I get the error in Cell 11.

```
---------------------------------------------------------------------------
PythonException                           Traceback (most recent call last)
PythonException: since Python.NET 3.0 int can not be converted to Enum implicitly. Use Enum(int_value)

The above exception was the direct cause of the following exception:

ArgumentException                         Traceback (most recent call last)
ArgumentException: since Python.NET 3.0 int can not be converted to Enum implicitly. Use Enum(int_value) in method ZOSAPI.Editors.LDE.ISurfaceTypeSettings GetSurfaceTypeSettings(ZOSAPI.Editors.LDE.SurfaceType) ---> Python.Runtime.PythonException: since Python.NET 3.0 int can not be converted to Enum implicitly. Use Enum(int_value)
   --- End of inner exception stack trace ---

The above exception was the direct cause of the following exception:

AggregateException                        Traceback (most recent call last)
AggregateException: One or more errors occurred. ---> System.ArgumentException: since Python.NET 3.0 int can not be converted to Enum implicitly. Use Enum(int_value) in method ZOSAPI.Editors.LDE.ISurfaceTypeSettings GetSurfaceTypeSettings(ZOSAPI.Editors.LDE.SurfaceType) ---> Python.Runtime.PythonException: since Python.NET 3.0 int can not be converted to Enum implicitly. Use Enum(int_value)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: since Python.NET 3.0 int can not be converted to Enum implicitly. Use Enum(int_value) in method ZOSAPI.Editors.LDE.ISurfaceTypeSettings GetSurfaceTypeSettings(ZOSAPI.Editors.LDE.SurfaceType) ---> Python.Runtime.PythonException: since Python.NET 3.0 int can not be converted to Enum implicitly. Use Enum(int_value)
   --- End of inner exception stack trace ---<---


The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[11], line 18
     16 cf_surf.Comment = 'Cornea Front'
     17 # Following statement not needed but given as example
---> 18 zp.functions.lde.surface_change_type(cf_surf, int(zp.constants.Editors.LDE.SurfaceType.Standard)) 
     20 cf_surf.Radius = cf_radius
     21 cf_surf.Conic = cf_conic

File ~\Code\ZOSPy\zospy\functions\lde.py:68, in surface_change_type(surf, newtype)
     65 newtype = proc_constant(constants.Editors.LDE.SurfaceType, newtype)
     67 # Apply
---> 68 newsurftypesettings = surf.GetSurfaceTypeSettings(newtype)
     69 surf.ChangeType(newsurftypesettings)

TypeError: No method matches given arguments for ILDERow.GetSurfaceTypeSettings: (<class 'int'>)
```

This error can be fixed by simply skipping the call to your wrapper function. For example the Cornea Front surface can now use

```
# cornea front
cf_surf = oss.LDE.InsertNewSurfaceAt(n_surf)
cf_surf.Comment = 'Cornea Front'
# Following statement not needed but given as example
# zp.functions.lde.surface_change_type(cf_surf, int(zp.constants.Editors.LDE.SurfaceType.Standard))
cf_surf.ChangeType(cf_surf.GetSurfaceTypeSettings(zp.constants.Editors.LDE.SurfaceType.Standard))
```

Apparently the update to the new python .net interface allows the enums to be passed around without conversion to integers. At least I think this is cause of the issue. It goes along with the notification you posted in the Readme.

I do not know how or when you want to tackle fixing this problem, so submitting an issue not a pull request.

**Comment by LucVV** [comment] 2023-02-15 20:54
Hi @julian-irwin-tfs,

Thank you for this report. Am I correct in assuming you are using Python.NET 3.0?
I ran into the same problem when updating to pythonnet 3.0. I started recoding several parts of the package but ran into similar problems with other calls to the API that were not fixable on the ZosPy side. Furthermore, the Zemax Staff [recommended not using pythonnet 3.0](https://community.zemax.com/zos-api-12/pythonnet-3-0-not-recommended-to-use-for-zosapi-python-3474). 

Since I ran into things I could not fix, I decided to wait until further updates from Zemax OpticStudio or Python.Net before changing the code and rather made Python.Net 2.5.2 required. 

Could you let me know which Python.Net version you are on?

**Comment by julian-irwin-tfs** [comment] 2023-02-15 21:24
I am indeed using pythonnet 3.0.1. 

I will work harder to get an older version of pythonnet up and running. Thanks so much for letting me know that Zemax Staff believe 3.0 is not supported. 

Also, thanks for the very nice python wrapper of ZOS API. It is a rather confusing API and I can tell that ZOSpy is going to get me up and running very quickly!

**Comment by julian-irwin-tfs** [comment] 2023-02-15 21:48
There is only pythonnet==2.5.2 support up through Python 3.8. I had only tried down to 3.9 when I submitted these issues. Everything seems to be working now. Sorry to bother you even though you had this exact advice posted on the front page!

**Comment by LucVV** [comment] 2023-02-17 06:39
No worries! I hope the use of 3.8 does not hamper you too much! I'll update the readme to state this requirement more specifically for now

**Comment by crnh** [comment] 2023-03-01 06:40
The Int to Enum conversion issue is already fixed in most of the code base, and will be fully fixed in an upcoming version of ZOSPy. 

We updated the documentation to point to a more relevant problem caused by Python.NET 3.x (which we also hope to fix soon).

**Closed** 2023-03-01 06:40 UTC
Labels: documentation
